---
title: "Carrera La Luz 2022"
subtile: "Actividad 1 - Métodos y Simulación Estadística"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#FFFFFF"
      fg: "#944903" 
      primary: "#944903" 
      base_font:
        google: Sen
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(ggplot2)
library(paqueteMET)

data("CarreraLuz22")

  
Theme2 = theme(
  axis.title.x = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  # axis.text.y = element_blank(),
  axis.text = element_text( size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8),  
  strip.text = element_text(size=8),
  title =element_text(size=8, face='bold')
)# tamaño letra por grupos

# subsets-----------------------------------------------------------------------
CarreraLuz22$sex[CarreraLuz22$sex == "M"]="Hombre"
CarreraLuz22$sex[CarreraLuz22$sex == "F"]="Mujer"
#-------------------------------------------------------------------------------
CarreraLuz22M = subset(CarreraLuz22, CarreraLuz22$sex=="Hombre")
CarreraLuz22F = subset(CarreraLuz22, CarreraLuz22$sex=="Mujer")

#-------------------------------------------------------------------------------
CarreraLuz22_c1M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="1. Juvenil")
CarreraLuz22_c2M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="2. Abierta")
CarreraLuz22_c3M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="3. Veteranos A")
CarreraLuz22_c4M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="4. Veteranos B")
CarreraLuz22_c5M = subset(CarreraLuz22M, CarreraLuz22M$categoria=="5. Veteranos C")


CarreraLuz22_c1F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="1. Juvenil")
CarreraLuz22_c2F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="2. Abierta")
CarreraLuz22_c3F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="3. Veteranos A")
CarreraLuz22_c4F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="4. Veteranos B")
CarreraLuz22_c5F = subset(CarreraLuz22F, CarreraLuz22F$categoria=="5. Veteranos C")
#-------------------------------------------------------------------------------

categoria= c("Juvenil","Abierta","Veteranos A", "Veteranos B","Veteranos C")
t2 = aggregate(CarreraLuz22$timerun/60, by=list(CarreraLuz22$categoria,CarreraLuz22$sex), FUN= summary)
t2=t2$x
t2m=t2[1:5,] 
row.names(t2m)=categoria
t2h=t2[6:10,] 
row.names(t2h)=categoria
```

# Tablero 1, gráficas.

Column {data-width=700 .tabset}
-----------------------------------------------------------------------

### Cantidad de mujeres y hombres - Categorías.

**Total participantes: 1922** Relación de cantidad de mujeres y hombres.

```{r, fig.height=1}
summary(CarreraLuz22$edad)

ggplot(CarreraLuz22,aes(x=sex))+geom_bar(aes(fill=categoria))
```

### Tiempos de carrera

```{r}
paleta6=c("#470", "#6B9493", "#F6E271", "#F6B916", "#F69312", "#BC6C25")
p1=ggplot(CarreraLuz22F, aes(y=timerun/60, x=categoria))+
  geom_jitter(color="#07AC6B", size=1, alpha=0.9) +
  aes(color=paleta6)+
  labs(title = " ",
       y= "tiempo - min",
       x= "categorías")+ 
  #facet_wrap(~ sex)
  #facet_grid(vars(sex), scale="free")+
  ylim(0,170)+
  Theme2

p1

```

### Tiempo mujeres categoría Abierta

```{r}
# seleccion de bases
dataFc2=subset(CarreraLuz22, (CarreraLuz22$sex=="Mujer" & CarreraLuz22$categoria=="2. Abierta")) # dataset de mujeres
x=dataFc2$timerun/60
hist(x, xlim=c(30,120), ylim=c(0,80),las=1,
main = " ",
xlab="tiempo (min)",
ylab = "frecuencia",
col ="#C247AC")
```

### Tiempo hombres categoría Abierta

```{r}
# seleccion de bases
dataMc2=subset(CarreraLuz22, (CarreraLuz22$sex=="Hombre" & CarreraLuz22$categoria=="2. Abierta")) # dataset de mujeres
x=dataMc2$timerun/60
hist(x, xlim=c(30,120), ylim=c(0,250),las=1,
main = " ",
xlab="tiempo (min)",
ylab = "frecuencia",
col ="#B3300D")
```


### Hombre por categorías

```{r, fig.height=2}
ggplot(CarreraLuz22M, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria)) + 
  # facet_wrap(~sex, ncol=1, labeller = labeller(dose = etiquetas))+
  labs(title = "", y= "tiempo - min", x= "categorías")+
  scale_fill_brewer() +
  #scale_fill_manual(values = c("#00070D", "#012447", "#034A94", "#0570E1", "#3998FB","#37B6FC"))+
  theme(legend.position = "none")
t2h
```

### Mujeres por categoría

```{r, fig.height=2}
ggplot(CarreraLuz22F, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria)) + 
  # facet_wrap(~sex, ncol=1, labeller = labeller(dose = etiquetas))+
  labs(title = "", y= "tiempo - min", x= "categorías")+
  scale_fill_brewer() +
  #scale_fill_manual(values = c("#00070D", "#012447", "#034A94", "#0570E1", "#3998FB","#37B6FC"))+
  theme(legend.position = "none")
t2m
```


# Tablero 2, indicadores.

Column {data-width=400}
-----------------------------------------------------------------------

### Registro de velocidad Máxima
```{r}
velocidadMin=round(10070/min(CarreraLuz22$timerun),2)
gauge(velocidadMin, min = 0, max = 6, symbol = 'm/s', gaugeSectors(
  success = c(4.5, 6), warning = c(2,4.4), danger = c(0, 1.9)
))
```

### Registro de velocidad Promedio
```{r}
velocidadProm=round(10070/mean(CarreraLuz22$timerun),2)
gauge(velocidadProm, min = 0, max = 6, symbol = 'm/s', gaugeSectors(
  success = c(4.5, 6), warning = c(2,4.4), danger = c(0, 1.9)
))
```

### Registro de velocidad Mínima
```{r}
velocidadMax=round(10070/max(CarreraLuz22$timerun),2)
gauge(velocidadMax, min = 0, max = 6, symbol = 'm/s', gaugeSectors(
  success = c(4.5, 6), warning = c(2,4.4), danger = c(0, 1.9)
))
```


Column { data-width=20 }
-----------------------------------------------------------------------
### minimo  {.value-box}
```{r}
valueBox(value =paste(round(mean(CarreraLuz22$timerun)/60,1), "min"), 
         caption = "Promedio tiempo Corredores", 
         icon = "fa-thumbs-up", 
         color = "#E6AA1F")
```


### velocidad  {.value-box}
```{r}
valueBox(value =paste(round(10070/mean(CarreraLuz22$timerun),2),"m/s"), # ud1$cierre, 
         caption = "Velocidad promedio", 
         icon = "fa-clock", 
         color = "#E6AA1F")
```


### distancia  {.value-box}
```{r}
valueBox(value = paste(10.07,"Km"), #ud1$min, 
         caption = "Distancia recorrida", 
         icon = "fa-solod fa-person-walking-arrow-right", 
         color = "#E6AA1F")
```


### volumen  {.value-box}
```{r}
valueBox(value = paste(length(CarreraLuz22$timerun),"atletas"), 
         caption = "Número de participantes", 
         icon = "fa-people", 
         color = "#E6AA1F")
```

### porcentaje  {.value-box}
```{r}
valueBox(value = paste(round(length(CarreraLuz22F$timerun)/length(CarreraLuz22$timerun)*100,2),"%"), 
         caption = "Porcentaje mujeres", 
         icon = "airplane-outline", 
         color = "#E6AA1F")
```





